import { FC } from 'react';
import { StaticDataAPI } from '../../../APIs/StaticDataAPI';
import { Link } from 'react-router-dom';
import { Map, MapStatus, MapToString } from '../../../Autogenerated/Backend';

interface MapCardComponentProps {
    map: Map;
}

export const MapCardComponent: FC<MapCardComponentProps> = ({ map }) => {
    const coverImageUrl = StaticDataAPI.FormMapCoverUrl(map);

    const bgColor = map.mapStatus === MapStatus.Available ? '' : 'bg-danger-subtle';

    return (
        <div className="col mb mb-sm-0 p-0 p-xl-3" key={map.id}>
            <div className={`card ${bgColor}`} style={{ width: 'auto', height: 'auto' }}>
                <div
                    className="card-img-top"
                    style={{
                        height: '15rem',
                        position: 'relative'
                    }}
                >
                    <img
                        src={coverImageUrl}
                        alt="Minimap image"
                        style={{
                            maxWidth: '100%',
                            maxHeight: '100%',
                            resize: 'both',
                            position: 'absolute',
                            top: 0,
                            bottom: 0,
                            left: 0,
                            right: 0,
                            margin: 'auto',
                            width: 'auto',
                            height: 'auto',
                            border: '1px solid black'
                        }}
                    />
                </div>
                <div className="card-body">
                    <h5 className="card-title">{MapToString(map)}</h5>
                    <Link to={`/maps/${map.id}`} className="btn btn-primary">
                        Подробнее
                    </Link>
                </div>
            </div>
        </div>
    );
};
