import { FC } from 'react';
import { MapCardComponent } from '../MapCard/MapCard';
import { Map } from '../../../Autogenerated/Backend';

interface MapListProps {
    maps: Map[];
}

export const MapListComponent: FC<MapListProps> = ({ maps }: MapListProps) => {
    return (
        <div className="container" style={{ display: 'flex' }}>
            <div className="row text-center" style={{ width: '100%' }}>
                <h5 className="p-0">Карты:</h5>
                <div className="row row-cols-3">
                    {maps.map((m) => (
                        <MapCardComponent map={m} key={m.id} />
                    ))}
                </div>
            </div>
        </div>
    );
};
