import { FC, useState, useEffect } from 'react';
import { MapAPI } from '../../../APIs/MapAPI';
import { LoadingIndicator } from '../../UI/LoadingIndicator';
import { StaticDataAPI } from '../../../APIs/StaticDataAPI';
import { Map, MapStatus, MapToString } from '../../../Autogenerated/Backend';
import { useNavigate } from 'react-router-dom';

interface MapPageComponentProps {
    id: number;
}

export const MapPageComponent: FC<MapPageComponentProps> = ({ id }: MapPageComponentProps) => {
    const [map, setMap] = useState<Map | null | undefined>(undefined);
    const [needsUpdate, setNeedsUpdate] = useState(true);

    const navigate = useNavigate();

    useEffect(() => {
        async function getData() {
            const gotMap = await MapAPI.GetMap(id);
            setMap(gotMap);
        }
        if (needsUpdate) {
            getData();
            setNeedsUpdate(false);
        }
        return () => {};
    }, [id, needsUpdate]);

    const onClickBack = () => {
        navigate(-1);
    };

    const backButton = (
        <button className="btn btn-secondary" onClick={onClickBack}>
            Назад
        </button>
    );

    if (map === null) {
        return <h2>Карта с номером #{id} не найдена</h2>;
    } else if (map == undefined) {
        return <LoadingIndicator />;
    }
    const coverImageUrl = StaticDataAPI.FormMapCoverUrl(map);
    const description = map.description ? <span>{map.description}</span> : <span className="text-body-secondary">Описание отсутствует</span>;

    const bgColor = map.mapStatus === MapStatus.Available ? '' : 'bg-danger-subtle';

    return (
        <div className={`card ${bgColor}`} key={map.id}>
            <div className="card-body">
                <div
                    style={{
                        height: '30rem',
                        position: 'relative'
                    }}
                >
                    <img
                        src={coverImageUrl}
                        alt="Minimap image"
                        style={{
                            maxWidth: '100%',
                            maxHeight: '100%',
                            resize: 'both',
                            position: 'absolute',
                            top: 0,
                            bottom: 0,
                            left: 0,
                            right: 0,
                            margin: 'auto',
                            width: 'auto',
                            height: 'auto',
                            border: '1px solid black'
                        }}
                    />
                </div>
                <h3 className="card-title">{map.name}</h3>
                {MapToString(map)}
                <br />
                {description}
            </div>
            {backButton}
        </div>
    );
};
